# pubspec.yaml
name: agrovision
description: App AgroVision con GetX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  camera: ^0.10.5+5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true